version: '3.8'
services:
  mssql-container:
    image: mcr.microsoft.com/mssql/rhel/server:2019-latest
    container_name: naughty_murdock
    environment:
      SA_PASSWORD: "someThingComplicated1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db-data:var/opt/mssql
  short-link-application:
    image: ashleynguyen07/short-link-application:v1.0.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://mssql-container:1433;databaseName=linkapplication;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "someThingComplicated1234"
    depends_on:
      - mssql-container
volumes:
  db-data: