spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=linkapplication;encrypt=true;trustServerCertificate=true
    username: sa
    password: someThingComplicated1234

security:
  oauth2:
    client:
      registration:
        google:
          clientId: 148552102427-f9ssttqui8ek06lqbeh10ics96t0vm75.apps.googleusercontent.com
          clientSecret: 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
          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
          scope:
            - email
            - profile
        github:
          clientId: 3087ab164dc570a1c72e
          clientSecret: e8e512354b45a78e35b3240a29f5d0ab31193ca9
          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
          scope:
            - user: email
            - read: user

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpiration: 1000 * 60 * 60 * 24 * 10
  cors:
    allowedOrigins: http://localhost:3000, http://localhost:8081
  oauth2:
    authorizedRedirectUri:
      - http://localhost:3000/oauth2/redirect
